/var/log/atmos/*.log {
    daily
    rotate 30
    compress
    delaycompress
    notifempty
    missingok
    create 0640 atmos atmos
    postrotate
        systemctl reload atmos-video
    endscript
}
